# For detailed feature config options, see:
# https://supabase.com/docs/guides/local-development/customizing-supabase-local-dev
# And for the full config reference:
# https://supabase.com/docs/reference/cli/config

[functions.send-booking-email]
enabled = true
verify_jwt = false
import_map = "./functions/send-booking-email/deno.json"
entrypoint = "./functions/send-booking-email/index.ts"

[functions.create-razorpay-order]
enabled = true
verify_jwt = true

[functions.create-razorpay-payment-link]
enabled = true
verify_jwt = true

[functions.verify-razorpay-payment]
enabled = true
verify_jwt = true

[functions.razorpay-webhook]
enabled = true
verify_jwt = false
